version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: my-postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
#    volumes:
#      - ./data:/var/lib/postgresql/data
